### PR TITLE
TXL-254: Fixed problem with language tag for categories in HTML

### PR DESCRIPTION
**Pull request by tombogle**
Also, fixed bug in handling radio buttons to set HandleUntranslatedQuestionsOption.
Also, added an option to omit the Scripture verses before each question.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/137)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/137)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[`Transcelerator/HtmlScriptGenerationSettings.cs` line 54 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vVtbV-NXulwfyKuqC:-O-vVtbWBGIkWShww8Cy:b6wdta4) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/Transcelerator/HtmlScriptGenerationSettings.cs#L54)):*
> ```Smalltalk
> 			get => !Properties.Settings.Default.OmitScriptureForQuestions;
> 			set => Properties.Settings.Default.OmitScriptureForQuestions = !value;
> 		}
> ```

I'm sure I'm just too being too lazy to figure it out, but I'm not sure I understand the relationship between the check box and the setting. 
The setting is per-user. So I guess the checkbox applies to all projects?
___
*[`TxlData/TxlDataTests/PhraseTranslationHelperTests.cs` line 4422 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vlhWC4d7CNGGQvIH4:-O-vlhWC4d7CNGGQvIH5:beht0aj) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/TxlData/TxlDataTests/PhraseTranslationHelperTests.cs#L4422)):*
> ```Smalltalk
> 			public bool IsGuess => false;
> 			public IReadOnlyList<string> Renderings => RenderingList;
> 		}
> ```

This file already contained mixed indentation. But your new lines also have a mix, even within the same line.
___
*[`TxlData/TxlDataTests/PhraseTranslationHelperTests.cs` line 4473 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vmPUsAGe6gX1O70jF:-O-vmPUsAGe6gX1O70jG:banltpp) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/TxlData/TxlDataTests/PhraseTranslationHelperTests.cs#L4473)):*
> ```Smalltalk
> 	        Assert.That(pth.GetCategoryName(1, out lang), Is.EqualTo("Specifics"));
> 	        Assert.That(lang, Is.Null);
>         }
> ```

Is it worth proving that if you provide a localizer, you still get the translated string?

**Comment by tombogle** [comment]
*[`Transcelerator/HtmlScriptGenerationSettings.cs` line 54 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vVtbV-NXulwfyKuqC:-O0ix0zO3PJWmShgqQfy:b-a0ru11) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/Transcelerator/HtmlScriptGenerationSettings.cs#L54)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm sure I'm just too being too lazy to figure it out, but I'm not sure I understand the relationship between the check box and the setting. 
The setting is per-user. So I guess the checkbox applies to all projects?
</blockquote></details>

In the UI, I wanted to be consistent about stating the positive: what will be included in the output if this option is selected, but I have a slight preference for boolean settings to default to false. (It probably doesn't make any difference, and I'm sure I'm not consistent.) So I worded the setting using Omit, but the property used in generating the script as Output. Maybe that was not helpful.
Transcelerator currently stores no project "settings" per se. The majority of users will work with a single project, so having it be per-user should be fine. Probably the ideal would be to have a standard per-user default and then per-project overrides, bit nobody's got time for that much complexity.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/137)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`Transcelerator/HtmlScriptGenerationSettings.cs` line 54 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vVtbV-NXulwfyKuqC:-O0jTvu03NMwS2WLNQLh:b-nzxiar) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/Transcelerator/HtmlScriptGenerationSettings.cs#L54)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

In the UI, I wanted to be consistent about stating the positive: what will be included in the output if this option is selected, but I have a slight preference for boolean settings to default to false. (It probably doesn't make any difference, and I'm sure I'm not consistent.) So I worded the setting using Omit, but the property used in generating the script as Output. Maybe that was not helpful.
Transcelerator currently stores no project "settings" per se. The majority of users will work with a single project, so having it be per-user should be fine. Probably the ideal would be to have a standard per-user default and then per-project overrides, bit nobody's got time for that much complexity.
</blockquote></details>

Yes, the flop of logic threw me a bit, too.
But I'll leave that up to you. You'll be the one in the code. : )

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/137)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`TxlData/TxlDataTests/PhraseTranslationHelperTests.cs` line 4422 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vlhWC4d7CNGGQvIH4:-O0jZA0ZEWQa11SrVA8c:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/TxlData/TxlDataTests/PhraseTranslationHelperTests.cs#L4422)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This file already contained mixed indentation. But your new lines also have a mix, even within the same line.
</blockquote></details>

Done.
___
*[`TxlData/TxlDataTests/PhraseTranslationHelperTests.cs` line 4473 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/137#-O-vmPUsAGe6gX1O70jF:-O0j_e6U99QT1BjKPMS1:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7ceee49e0060ee6fe3d1cbbf45023162ecf6c1bc/TxlData/TxlDataTests/PhraseTranslationHelperTests.cs#L4473)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it worth proving that if you provide a localizer, you still get the translated string?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/137)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
