### PR TITLE
Added/organized questions for Haggai and removed attributes with default values 

### PR DESCRIPTION
**Pull request by tombogle**
Manually worked through the Door43 questions for Haggai, adding/adjusting them as necessary and also adding my own questions and Alternative forms. (This will serve as a model for what it might look like to fully incorporate the Door43 questions.)
As part of that, also introduced a new source attribute (currently not used in TXL and only applied to the HAG questions). Stripped off unnecessary attributes with default values in TxlQuestions.xml to reduce file size.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/126)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
How would you like me to contribute to this review? Would you like me to read through the questions, etc.?
Or should I just be looking for technical problems.
I don't see any of the latter.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/126#-:-Nwklyud-sDYa4sO8P3v:brt17mj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Comment by tombogle** [comment]
At whatever level you feel is appropriate. Yeah, I don't expect there would be any technical problems because the questions load properly in Transcelerator. For sure, if you want to evaluate the content, I'm always open to good feedback and another set of eyes can't hurt. But if you don't have time and just want to rubber-stamp it, that's fine.

**Review by andrew-polk — COMMENTED** [review]
The tools make it viritually impossible to review TxlQuestions with inline comments.

- Typo in "The people were buidling and enjoying their own..."
- <A\>OR on September 21 of the second year of King Darius’s reign</A\> is missing a period
- <A\>To Zerubbabel the son of Shealtiel, governor of Judah, and to Joshua the son of Jehozadak, the high priest</A\> is missing a period
- The answers to HAG 2.8 and HAG 2.9 are missing periods.
- The answer to HAG 2.20 has no period.

That's all I have from my super brief review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/126#-:-NwqaLSO5gp6Tzx-SibF:b-52mjr7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Comment by tombogle** [comment]
Good catch on the typo. I've tried to make capitalization and punctuation in answers more consistent. (Answers that are not complete sentences should start with a lowercase letter. Answers that are complete sentences should have sentence-ending punctuation.) In another PR, I'll do a little more cleanup on that outside of HAG.

**Pull request merged**
