### PR TITLE
TXL-19: Support localization of the UI using L10NSharp

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/16)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 24 of 24 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/16)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

**Comment by tombogle** [comment]
___
*[SilUtils/SerializationHelper.cs, line 36 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/16#-MFqT359D1mRHX3M9OH4:-MHBVnSI74wdEbtk0Tbt:b-tuczfx) ([raw file](https://github.com/sillsdev/transcelerator/blob/67ff43ddfa35841dcd08b222e57ff99c45dc1dc1/SilUtils/SerializationHelper.cs#L36)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sure we don't want to use this from libpalaso?
I guess if is not there already, you're thinking it isn't worth the overhead of adding it?
It really is problematic that we have all (myself included) started thinking adding to libpalaso is not worth it. "We" should do something about that...
</blockquote></details>

I removed everything from this file except for this one method. Everything else is in libpalaso, and I'm using it from there now. I guess this method could be added to the SerializationHelper class in libpalaso, but I wasn't very sure of its general usefulness.

**Comment by tombogle** [comment]
___
*[Transcelerator/RenderingSelectionRulesDlg.cs, line 179 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/16#-MFqXRot6QE7ytahxyhq:-MHBdxu6D70_H59tAzGL:bact1x2) ([raw file](https://github.com/sillsdev/transcelerator/blob/67ff43ddfa35841dcd08b222e57ff99c45dc1dc1/Transcelerator/RenderingSelectionRulesDlg.cs#L179)):*
> ```
> m_listRules_SelectedIndexChanged(m_listRules, new EventArgs());
> ```
I just looked over this code, and realized that this label's Text is empty and will always be filled in programmatically. It is not a format string and does not need to be localizable at all. And there are no other strings in this this dialog that do contain formatting specifiers, so there is no need at all for handling StringsLocalized.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/16)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[Transcelerator/RenderingSelectionRule.cs, line 348 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/16#-MFqWfEY35WRtce13uFw:-MHBXNF16twYw4ndX9ZA:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/67ff43ddfa35841dcd08b222e57ff99c45dc1dc1/Transcelerator/RenderingSelectionRule.cs#L348)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This ID and the one above it are wrong.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 33 of 33 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
> Reviewed 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
