### PR TITLE
Upgraded to .Net Framework 4.8 and upgraded a lot of dependencies

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/115)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
The project which required .NET Framework 4.5.2 in the TC build was CustomInstallerActions.csproj. I don't see any changes to that project here.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/115#-:-NVGKtOc3A1f-UvCHFNj:bqec4hk)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/115)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Comment by tombogle** [comment]
*[`DataIntegrityTests/DataIntegrityTests.csproj` line 81 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/115#-NVGKGkB0bmITy-vNj5m:-NVVDTHQ9AyRj1OBMeWT:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/a3902b2a8f0eb67cc8da0af50e9d9e42de460801/DataIntegrityTests/DataIntegrityTests.csproj#L81)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I expected these upgrades of NUnit.ConsoleRunner to require a change in the .proj file.
Maybe one of the test projects still pulls in 3.15.2?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
