### PR TITLE
Update extension template

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/143)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/143)* status: all files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`contributions/localizedStrings.json` line 5 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4B1EsZ7Mi_gL97Kuu3:-O4B1EsZ7Mi_gL97Kuu4:bdc3bi) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/contributions/localizedStrings.json#L5)):*
> ```JSON
>   "localizedStrings": {
>     "en": {
>       "%mainMenu_openTranscelerator%": "Transcelerator",
> ```

Should this still say open?
___
*[`src/main.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4B1xmgC7Q3rN_jvkeX:-O4B1xmgC7Q3rN_jvkeY:bhp6n63) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/main.ts#L13)):*
> ```XML
> import transceleratorMain from './transcelerator-main.web-view?inline';
> import transceleratorMainReactStyles from './transcelerator-main.web-view.scss?inline';
> import helpHtml from '../Docs/Help Topics/en/Home.htm?inline';
> ```

.html?
___
*[`src/main.ts` line 33 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4BIErd39XyOHzsKw13:-O4BIErd39XyOHzsKw14:b-39qeb) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/main.ts#L33)):*
> ```XML
>       ...savedWebView,
>       title: 'Transcelerator Help',
>       // eslint-disable-next-line no-type-assertion/no-type-assertion
> ```

Comment explaining type assert
___
*[`src/main.ts` line 80 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4BHzB62mIrFxArgK-B:-O4BHzB62mIrFxArgK-C:b-hbvzq8) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/main.ts#L80)):*
> ```XML
>     context.executionToken,
>     '../Transcelerator/TxlQuestionWords.xml',
>   ); */
> ```

Do you still need this?
___
*[`src/types/transcelerator.d.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4BIvM8CJbuo1KmI2hy:-O4BIvM8CJbuo1KmI2hz:bmyew8d) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/types/transcelerator.d.ts#L15)):*
> ```XML
>    */
>   export type TranslationConfirmedEvent = {
>     origEnglishQuestion: string;
> ```

Should be original ? Code style guide says avoid abbreviations

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/143)* status: 39 of 44 files reviewed, 5 unresolved discussions (waiting on @jolierabideau)

___
*[`contributions/localizedStrings.json` line 5 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4B1EsZ7Mi_gL97Kuu3:-O4BUU5N5s7DAEwQH1jw:buemnhh) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/contributions/localizedStrings.json#L5)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Should this still say open?
</blockquote></details>

Maybe. In Paratext 9, it just says Transcelerator. Most other "tools" (e.g., Biblical Terms) don't use a verb like open, but "Open ext collection" does. Ultimately, I'm not sure where in the menu system this is going to want to live. 
___
*[`src/main.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4B1xmgC7Q3rN_jvkeX:-O4CjxNc8Ofm5K5jOMvu:bf4nhf5) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/main.ts#L13)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

.html?
</blockquote></details>

The files (which already exist and are in use in the Paratext 9 plugin) have an .htm extension. Platform seems to be fine with that. They could fairly easily be renamed if necessary, but I'm not aware of a compelling reason.
___
*[`src/main.ts` line 33 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4BIErd39XyOHzsKw13:-O4CkhYoBhOUiammgo7b:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/main.ts#L33)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Comment explaining type assert
</blockquote></details>

Done.
___
*[`src/main.ts` line 80 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4BHzB62mIrFxArgK-B:-O4Ckl9yBjvPlJkNj0N_:bmsiw5a) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/main.ts#L80)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Do you still need this?
</blockquote></details>

Not sure it will end up here, but it's future code that I expect to want.
___
*[`src/types/transcelerator.d.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4BIvM8CJbuo1KmI2hy:-O4ClDEdB1Wfy4rVF0ht:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/src/types/transcelerator.d.ts#L15)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Should be original ? Code style guide says avoid abbreviations
</blockquote></details>

Done.

**Review by jolierabideau — APPROVED** [review]
Looks great Tom!

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-:-O4GMhos1lAXZz5O308K:bhts6b7)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`contributions/localizedStrings.json` line 5 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4B1EsZ7Mi_gL97Kuu3:-O4GCY5y9RNsR1d6IrP-:b1obssi) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/contributions/localizedStrings.json#L5)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Maybe. In Paratext 9, it just says Transcelerator. Most other "tools" (e.g., Biblical Terms) don't use a verb like open, but "Open ext collection" does. Ultimately, I'm not sure where in the menu system this is going to want to live.
</blockquote></details>

I meant how the `localizeKey` says "openTranscelerator" and the localized value is just "Transcelerator"

**Comment by tombogle** [comment]
*[`contributions/localizedStrings.json` line 5 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/143#-O4B1EsZ7Mi_gL97Kuu3:-O4GTn92AdwHtNrPiujf:b-s1gsfj) ([raw file](https://github.com/sillsdev/Transcelerator/blob/e46a93ab43c7dfe2475b470998a43480d70b1ef9/contributions/localizedStrings.json#L5)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

I meant how the `localizeKey` says "openTranscelerator" and the localized value is just "Transcelerator"
</blockquote></details>

Gotcha. I don't know that I have strong feelings either way. As it is, it corresponds to the command name.

**Pull request merged**
