### PR TITLE
Added TM mark to indicate trademarked names

### PR DESCRIPTION
**Pull request by tombogle**
Did this for Transcelerator and other SIL products.
This involved changing approach to laying out splash screen and about box. Replaced (outdated) SF logo with a generic MUI icon and updated HTML help file to include PTXPrint. Also fixed minor layout issue in ScriptureForgeInfoDlg. Also, disabled using links in Credits and License HTML to access websites if Paratext Internet access is disabled.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/131)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/131)* status: all files reviewed, 5 unresolved discussions (waiting on @tombogle)

___
*[`Docs/Help Topics/en/Home.htm` line 14 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZf2YkEMXqxRF2hPdl:-NxZf2YkEMXqxRF2hPdm:b-ugg5oe) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Docs/Help%20Topics/en/Home.htm#L14)):*
> ```HTML
> <body lang=EN-US>
> 
>   <h2>Welcome to Transcelerator™ Help</h2>
> ```

What's the benefit?
___
*[`Installer/Installer.wxs` line 296 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZfsdk50D35sEuTuaa:-NxZfsdk50D35sEuTuab:buy80wo) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Installer/Installer.wxs#L296)):*
> ```XML
>           </Component>
>           <Component Guid="*">
>             <File Id="Microsoft.Web.WebView2.Core.dll_P9Beta" ShortName="mwwv2c9b.dll" KeyPath="yes" Name="Microsoft.Web.WebView2.Core.dll"/>
> ```

Adding wv2 feels pretty heavy weight for what I understand your use case to be.

Have you looked at how much this adds to your installer?

What's driving this?

Maybe we should discuss...
___
*[`Transcelerator/TxlInfo.cs` line 125 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZiGG73qY6DdkIqzbm:-NxZiGG73qY6DdkIqzbn:bnblixj) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Transcelerator/TxlInfo.cs#L125)):*
> cause an exception

I thought you could just escape them by doubling them or something.
___
*[`Transcelerator/TxlInfo.cs` line 126 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZi0P91gA731dn5upz:-NxZi0P91gA731dn5uq-:bxdvaqn) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Transcelerator/TxlInfo.cs#L126)):*
> and external

typo
___
*[`Transcelerator/DevResources/Readme.txt` line 1 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZhGesC6NBhL10_Ud_:-NxZhGesC6NBhL10_Uda:b-vu4dge) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Transcelerator/DevResources/Readme.txt#L1)):*
> pert

typo

**Comment by tombogle** [comment]
*[`Docs/Help Topics/en/Home.htm` line 14 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZf2YkEMXqxRF2hPdl:-Nxlv2J77PXCB7_boFXY:b-7o9vs5) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Docs/Help%20Topics/en/Home.htm#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What's the benefit?
</blockquote></details>

This is something that is being rolled out SIL-wide. At the IP meeting last week, we were asked to do this for all SIL software. @alexcrum is coordinating the effort and can share the document with you that has the specific guidelines. I think he plans to walk through the process with each team/product, but I got inspired and decided to try to make it happen for Transcelerator. The timing seemed right since I needed to upgrade the way I am referring to ScriptureForge (outdated icon) and PTXPrint (incomplete information). I did not originally anticipate it being this much work, but since Transcelerator will be moving to become a Platform.Bible extension, this felt like a reasonable (baby) step toward getting away from Winforms.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/131)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`Docs/Help Topics/en/Home.htm` line 14 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZf2YkEMXqxRF2hPdl:-Nxn2s2J9-yrBP6mBs02:b-1jizgm) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Docs/Help%20Topics/en/Home.htm#L14)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

This is something that is being rolled out SIL-wide. At the IP meeting last week, we were asked to do this for all SIL software. @alexcrum is coordinating the effort and can share the document with you that has the specific guidelines. I think he plans to walk through the process with each team/product, but I got inspired and decided to try to make it happen for Transcelerator. The timing seemed right since I needed to upgrade the way I am referring to ScriptureForge (outdated icon) and PTXPrint (incomplete information). I did not originally anticipate it being this much work, but since Transcelerator will be moving to become a Platform.Bible extension, this felt like a reasonable (baby) step toward getting away from Winforms.
</blockquote></details>

I guess I dodged that meeting somehow. Never heard about it.

I still don't see the value. And it seems like a lot of work to impose. But I guess I'll wait to hear more.
Maybe this doesn't affect Bloom since it is registered.
___
*[`Transcelerator/TxlInfo.htm` line 9 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-Nxn40F95lpELYiRMFwR:-Nxn40F95lpELYiRMFwS:bpdshmz) ([raw file](https://github.com/sillsdev/Transcelerator/blob/f4ea47678ba7f2daaf5af829190191a312e77271/Transcelerator/TxlInfo.htm#L9)):*
> string.Fformat

typo

**Comment by tombogle** [comment]
*[`Docs/Help Topics/en/Home.htm` line 14 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-NxZf2YkEMXqxRF2hPdl:-Nxn4cc7D2MzCCdfYRBI:b-ac0dp6) ([raw file](https://github.com/sillsdev/Transcelerator/blob/7f5d4bc136da407607af7b4116ccd6246163aa82/Docs/Help%20Topics/en/Home.htm#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess I dodged that meeting somehow. Never heard about it.

I still don't see the value. And it seems like a lot of work to impose. But I guess I'll wait to hear more.
Maybe this doesn't affect Bloom since it is registered.
</blockquote></details>

Part of the longer-term game plan is to decide which products should have their trademarks registered. From some website: The Trademark symbol (™), “The TM Symbol” is often used on logos, names, phrases, or words. The TM Symbol is used proactively by companies to indicate the mark is their own exclusive property. The Trademark ™ symbol has no legal meaning, but can be used on unregistered marks as a “**no trespassing**” sign.

**Comment by tombogle** [comment]
This is still in DRAFT because there is a DLL conflict (fails to load correct version of SIL.Core) when running from released version, in the Filter by Reference dialog. _Maybe_ solvable by going to a new release version of libpalaso.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/131)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`Transcelerator/HelpAboutDlg.Designer.cs` line 119 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-Nxt7f_h8A9kzYLfBA8u:-Nxt7f_h8A9kzYLfBA8v:b4codhw) ([raw file](https://github.com/sillsdev/Transcelerator/blob/003b3483536cabf462de9552fe4be6ef9c72a797/Transcelerator/HelpAboutDlg.Designer.cs#L119)):*
> ```Smalltalk
>             this.ShowIcon = false;
>             this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Show;
>             this.Text = "About {0}";
> ```

Is this working? I don't see where you do the formatting.
___
*[`Transcelerator/TxlPlugin.cs` line 135 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-Nxt88Pn991q9APifK_b:-Nxt88Pn991q9APifK_c:b-y3txkn) ([raw file](https://github.com/sillsdev/Transcelerator/blob/003b3483536cabf462de9552fe4be6ef9c72a797/Transcelerator/TxlPlugin.cs#L135)):*
> ```Smalltalk
> 					"Unable to obtain exclusive write access to data that belongs to {1}: {0}",
> 					"Param 0: key that indicates the data file that was to be written;" +
> 					"Param 1: \"Transcelerator\" (plugin name)"), fileName, kPluginName);
> ```

If I understand, the main purpose of this PR is to add TM to Trancelerator and other product names. But I don't where you added TM to `kPluginName`.

**Comment by tombogle** [comment]
*[`Transcelerator/TxlPlugin.cs` line 135 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-Nxt88Pn991q9APifK_b:-NxuHfNK6gw__vg1vg4U:biug8aa) ([raw file](https://github.com/sillsdev/Transcelerator/blob/003b3483536cabf462de9552fe4be6ef9c72a797/Transcelerator/TxlPlugin.cs#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I understand, the main purpose of this PR is to add TM to Trancelerator and other product names. But I don't where you added TM to `kPluginName`.
</blockquote></details>

According to the guidelines, the TM is only supposed to be added to the "first" usage in any context. So by putting it on the Splash screen, the Help About box, and the first use in the Home page of the Help, I think I've met the requirement.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/131)* status: 50 of 51 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`Transcelerator/HelpAboutDlg.Designer.cs` line 119 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-Nxt7f_h8A9kzYLfBA8u:-NxuGu1SAFUncLp0Qoms:besmjw2) ([raw file](https://github.com/sillsdev/Transcelerator/blob/003b3483536cabf462de9552fe4be6ef9c72a797/Transcelerator/HelpAboutDlg.Designer.cs#L119)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this working? I don't see where you do the formatting.
</blockquote></details>

It's in HelpAboutDlg.HandleStringsLocalized. Not sure why Reviewable is showing it as having changed but claiming that 0 lines changed, when that file actually grew by more than 50%!
___
*[`Transcelerator/TxlInfo.htm` line 9 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/131#-Nxn40F95lpELYiRMFwR:-NxuH_pG3Rf67bSKw9TJ:b-886gsx) ([raw file](https://github.com/sillsdev/Transcelerator/blob/f4ea47678ba7f2daaf5af829190191a312e77271/Transcelerator/TxlInfo.htm#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> string.Fformat

typo
</blockquote></details>

Fixed

**Pull request merged**
