### PR TITLE
Changed serialization to specify utf-8 so files would not claim to be utf-16

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/21)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/21)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[Transcelerator/DataFileAccessor.cs, line 72 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/21#-MIzVhGCBml0O_tVxSMg:-MIzVhGD5hsc1pHTEcWM:b-jzbrmr) ([raw file](https://github.com/sillsdev/transcelerator/blob/ae779eae4680ff1bfcde5ceb392e33492d4aab91/Transcelerator/DataFileAccessor.cs#L72)):*
> ```Smalltalk
> 		private T CheckDataIsXmlSerializable<T>(T data)
>         {
> 			if (data is IConvertible)
> ```

You mention this is to prevent calling the wrong thing (I assume the wrong overload?). Why not just check for string here instead of IConvertible?

**Comment by tombogle** [comment]
___
*[Transcelerator/DataFileAccessor.cs, line 72 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/21#-MIzVhGCBml0O_tVxSMg:-MIz_89qCIo-rhbKHYpZ:b-2wrero) ([raw file](https://github.com/sillsdev/transcelerator/blob/ae779eae4680ff1bfcde5ceb392e33492d4aab91/Transcelerator/DataFileAccessor.cs#L72)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

You mention this is to prevent calling the wrong thing (I assume the wrong overload?). Why not just check for string here instead of IConvertible?
</blockquote></details>

I thought about it. What I really wanted to do was use a constraint, but unfortunately you can't do a constraint that something does not implement a particular interface. In searching for an appropriate way to do the constraint, I discovered that all the built-in value types are IConvertible. Since I would presume that none of those would ever be valid types to serialize as XML, that seemed like a fair check. But I don't feel terribly strongly about it.

**Review by FoolRunning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/21#-:-MIzi3bQ4ZxlMNQlscLT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[Transcelerator/DataFileAccessor.cs, line 72 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/21#-MIzVhGCBml0O_tVxSMg:-MIzhx2C7_P1jxBor1Xw:b-9jsr0r) ([raw file](https://github.com/sillsdev/transcelerator/blob/ae779eae4680ff1bfcde5ceb392e33492d4aab91/Transcelerator/DataFileAccessor.cs#L72)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I thought about it. What I really wanted to do was use a constraint, but unfortunately you can't do a constraint that something does not implement a particular interface. In searching for an appropriate way to do the constraint, I discovered that all the built-in value types are IConvertible. Since I would presume that none of those would ever be valid types to serialize as XML, that seemed like a fair check. But I don't feel terribly strongly about it.
</blockquote></details>

Okay, that makes sense. I was just curious. It's fine the way it is.

**Review by FoolRunning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
