### PR TITLE
TXL-246: Prevent attempt to create a ScrVerseRefAdapter using out-of-range chapter or verse

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/107)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/107)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`Transcelerator/ScrVerseRefAdapter.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/107#-NPwHJm604Q7NcoZmvhA:-NPwHJm604Q7NcoZmvhB:b-1imcmc) ([raw file](https://github.com/sillsdev/Transcelerator/blob/91a1b50d80bbd1b1053663cd8cd4062bd796bed5/Transcelerator/ScrVerseRefAdapter.cs#L86)):*
> ```Smalltalk
>                 }
> 
>                 verseRef = m_verseRef.Versification.CreateReference(bookNum, c, v);
> ```

With this change, you can't handle verse segments (3a, 3b, etc.) since it will fail to parse as an int. Is that your intention?

**Comment by tombogle** [comment]
*[`Transcelerator/ScrVerseRefAdapter.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/107#-NPwHJm604Q7NcoZmvhA:-NPwIPFq6zed0dCzr6OU:b-9yeg7h) ([raw file](https://github.com/sillsdev/Transcelerator/blob/91a1b50d80bbd1b1053663cd8cd4062bd796bed5/Transcelerator/ScrVerseRefAdapter.cs#L86)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

With this change, you can't handle verse segments (3a, 3b, etc.) since it will fail to parse as an int. Is that your intention?
</blockquote></details>

I didn't know you could put verse segments in that control. TXL definitely wouldn't know what to do with them. I'll try it and see what happens. What I would really like is a way to have the control itself reject out-of-range values or to be able to detect them and disable the OK button or something like that. correcting the values as part of the acceptance logic still lets the user close the dialog without really seeing what happened, and that could be confusing.

**Comment by tombogle** [comment]
*[`Transcelerator/ScrVerseRefAdapter.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/107#-NPwHJm604Q7NcoZmvhA:-NPwgc7kEsZCkxupRmU3:b-om5vk2) ([raw file](https://github.com/sillsdev/Transcelerator/blob/91a1b50d80bbd1b1053663cd8cd4062bd796bed5/Transcelerator/ScrVerseRefAdapter.cs#L86)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I didn't know you could put verse segments in that control. TXL definitely wouldn't know what to do with them. I'll try it and see what happens. What I would really like is a way to have the control itself reject out-of-range values or to be able to detect them and disable the OK button or something like that. correcting the values as part of the acceptance logic still lets the user close the dialog without really seeing what happened, and that could be confusing.
</blockquote></details>

There is an AllowVerseSegments property, and that is set to false, so no worries with that.

**Comment by tombogle** [comment]
*[`Transcelerator/ScrVerseRefAdapter.cs` line 86 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/107#-NPwHJm604Q7NcoZmvhA:-NPwkpG_41-zl_d_uirE:b86rlqw) ([raw file](https://github.com/sillsdev/Transcelerator/blob/91a1b50d80bbd1b1053663cd8cd4062bd796bed5/Transcelerator/ScrVerseRefAdapter.cs#L86)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

There is an AllowVerseSegments property, and that is set to false, so no worries with that.
</blockquote></details>

I just pushed an improvement that is more likely to have the desired behavior.

**Pull request merged**
