### PR TITLE
Refactoring to split UI from logic

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/121)

### CODE REVIEW

**Comment by tombogle** [comment]
There is still **more** work to be done on this. But I've got it to a usable state now, and I think it happens to fix an actual bug, so I'm inclined to merge it and then do remaining work on a piecemeal basis as needed.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Hit the easy stuff so far.
Publishing what I have in case you want to act on any of it now.

> Reviewed 164 of 171 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-:-NpafO6H7DUNC0gYCs9U:b-8zdcfu)* status: 162 of 171 files reviewed, 7 unresolved discussions (waiting on @tombogle)

___
*[`Installer/Installer.wxs` line 4 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NoxYzVp0PF_0DJRH_wN:-NoxYzVp0PF_0DJRH_wO:b-qevr0z) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/Installer/Installer.wxs#L4)):*
> ```XML
> 
> 
> <?define Property_ProductVersion = "3.1.0" ?>
> ```

Did you mean to define this?
___
*[`Transcelerator/CreditsAndLicense.htm` line 35 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Noxd80y-DY4dfhIP_Iz:-Noxd80y-DY4dfhIP_J-:bb6ht39) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/Transcelerator/CreditsAndLicense.htm#L35)):*
> ```HTML
>         <h1>License</h1>
>         <p>This software and the resources it contains are licensed under <a href="http://sil.mit-license.org/">The MIT License</a>.</p>
>         <p>Copyright © 2011-2023, SIL International</p>
> ```

2024
___
*[`Transcelerator/UNSQuestionsDialog.cs` line 658 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Noxf5SABPdpgIcLIh_p:-Noxf5SABPdpgIcLIh_q:b-68sgxp) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/Transcelerator/UNSQuestionsDialog.cs#L658)):*
> ```Smalltalk
> 		private void SetLocalizer(string preferredUiLocale)
> 		{
>             if (preferredUiLocale == "ar")
> ```

Variable indentations here (if you care)
___
*[`TxlShared/TxlData.cs` line 14 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpaeZbO45E2hrktIRcd:-NpaeZbO45E2hrktIRce:b21gwvc) ([raw file](https://github.com/sillsdev/Transcelerator/blob/d53ae2811373eacd0c2a4ca190099b1d19bf8135/TxlShared/TxlData.cs#L14)):*
> ```Smalltalk
> namespace SIL.Transcelerator
> {
>     public static class TxlData
> ```

Is it strange to have a class called TxlData in a project called TxlShared when you have a project called TxlData?

What is the purpose of this class? Maybe trying to summarize it in a comment would help come up with a meaningful name.
___
*[`TxlData/IPhraseTranslationHelper.cs` line 4 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Noxhcu85SmoOvS3Wm4X:-Noxhcu85SmoOvS3Wm4Y:bkf5h0r) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/TxlData/IPhraseTranslationHelper.cs#L4)):*
> ```Smalltalk
> #region // Copyright (c) 2023, SIL International.
> // <copyright from='2021' to='2023' company='SIL International'>
> //		Copyright (c) 2023, SIL International.   
> ```

There are quite a few files where the copyright got updated to 2023.
___
*[`TxlData/UsfmStyleBasedCss.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Npac3mB0mzP5hokVDWn:-Npac3mB0mzP5hokVDWo:baidsz5) ([raw file](https://github.com/sillsdev/Transcelerator/blob/d53ae2811373eacd0c2a4ca190099b1d19bf8135/TxlData/UsfmStyleBasedCss.cs#L3)):*
> ```Smalltalk
> using System;
> using System.Collections.Generic;
> // TODO: Remove dependency on System.Drawing for version of Transcelerator that will work in
> ```

Still a TODO?
Several more in this file.
___
*[`TxlData/TxlDataTests/PhraseTranslationHelperTests.cs` line 4499 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Npad-_TCKHc32xFCr_2:-Npad-_TCKHc32xFCr_3:b-tvm7go) ([raw file](https://github.com/sillsdev/Transcelerator/blob/d53ae2811373eacd0c2a4ca190099b1d19bf8135/TxlData/TxlDataTests/PhraseTranslationHelperTests.cs#L4499)):*
> ```Smalltalk
> 		#endregion
> 	}
> }
> ```

By the way, apparently something has changed line ending or something. Reviewable is showing just about every line for most of these files.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 171 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/121)* status: 165 of 171 files reviewed, 7 unresolved discussions (waiting on @tombogle)

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/121)* status: 152 of 173 files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @tombogle)

___
*[`Installer/Installer.wxs` line 4 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NoxYzVp0PF_0DJRH_wN:-Npag6lr1zy3wlgk0iX9:b-d93wjk) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/Installer/Installer.wxs#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you mean to define this?
</blockquote></details>

Yikes! No. Good catch.
___
*[`Transcelerator/CreditsAndLicense.htm` line 35 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Noxd80y-DY4dfhIP_Iz:-NpagLhs8Y6nnWIEF8UG:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/Transcelerator/CreditsAndLicense.htm#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

2024
</blockquote></details>

Done.
___
*[`Transcelerator/UNSQuestionsDialog.cs` line 658 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Noxf5SABPdpgIcLIh_p:-NpaqYQDA1-K-L7Z3oXP:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/Transcelerator/UNSQuestionsDialog.cs#L658)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Variable indentations here (if you care)
</blockquote></details>

Done.
___
*[`TxlData/IPhraseTranslationHelper.cs` line 4 at r1](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Noxhcu85SmoOvS3Wm4X:-NpaqdkQ4oZ3ff28b7lF:b-obxmuv) ([raw file](https://github.com/sillsdev/Transcelerator/blob/18d928dd6ab95f583eec75b83f345ecea3c27e87/TxlData/IPhraseTranslationHelper.cs#L4)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There are quite a few files where the copyright got updated to 2023.
</blockquote></details>

Yeah, cuz I actually made those edits in 2023, not 2024. I don't know how much I actually care, especially since this is MIT licensed open source. A lot (maybe most) SIL code doesn't use per-file copyright statements. Transcelerator inherited from FW, which does (or did).
___
*[`TxlData/UsfmStyleBasedCss.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Npac3mB0mzP5hokVDWn:-Nparav88OCB_HOUj0kl:b8ifa1x) ([raw file](https://github.com/sillsdev/Transcelerator/blob/d53ae2811373eacd0c2a4ca190099b1d19bf8135/TxlData/UsfmStyleBasedCss.cs#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Still a TODO?
Several more in this file.
</blockquote></details>

Yes. Sadly. But I think I want to release this bug fix before I upgrade to ParatextPluginInterfaces 2.0.100.
___
*[`TxlData/TxlDataTests/PhraseTranslationHelperTests.cs` line 4499 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-Npad-_TCKHc32xFCr_2:-Npas9fm4kOyC19wQjxb:b-bam0vj) ([raw file](https://github.com/sillsdev/Transcelerator/blob/d53ae2811373eacd0c2a4ca190099b1d19bf8135/TxlData/TxlDataTests/PhraseTranslationHelperTests.cs#L4499)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

By the way, apparently something has changed line ending or something. Reviewable is showing just about every line for most of these files.
</blockquote></details>

According to .editorconfig, all .cs files should have CRLF. That appears to be what they are now. I guess the previous version must not have. Seems like Reviewable should make it easy to ignore whitespace differences: https://docs.reviewable.io/files.html?highlight=whitespace#collapsed-sections
___
*[`TxlShared/TxlData.cs` line 14 at r2](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpaeZbO45E2hrktIRcd:-NpavYr2Dia26WpzWC3f:b-ea8jlo) ([raw file](https://github.com/sillsdev/Transcelerator/blob/d53ae2811373eacd0c2a4ca190099b1d19bf8135/TxlShared/TxlData.cs#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it strange to have a class called TxlData in a project called TxlShared when you have a project called TxlData?

What is the purpose of this class? Maybe trying to summarize it in a comment would help come up with a meaningful name.
</blockquote></details>

Probably started its life inside TxlData project. There was no good name for it, so I broke it into two classes with good names.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/121)* status: 167 of 173 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`Transcelerator/RenderingSelectionRulesDlg.cs` line 218 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpuMfR1BbmMtkLOvz5e:-NpvkI8m-WGDFdfwwZnf:b-vgda6d) ([raw file](https://github.com/sillsdev/Transcelerator/blob/959007935c1458e61709ff2305af5e209ca47aa4/Transcelerator/RenderingSelectionRulesDlg.cs#L218)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I didn't really review this, assuming it came as is from the other file.
Let me know if I need to look more carefully.
</blockquote></details>

Yeah, I don't think it really changed.
___
*[`TxlData/IScriptGenerationSettings.cs` line 38 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpuKQvv9eMuxTsOqlXr:-NpvlJ6iAZiEoNAdVpht:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/959007935c1458e61709ff2305af5e209ca47aa4/TxlData/IScriptGenerationSettings.cs#L38)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Nit:
The other properties have LWC (capitalized)
</blockquote></details>

Done.
___
*[`TxlData/SubstitutionMatchGroup.cs` line 30 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpuM5Gt9T_H6shsrM8b:-NpvmdFQ1Ris7Rj6gcBi:bixnkfv) ([raw file](https://github.com/sillsdev/Transcelerator/blob/959007935c1458e61709ff2305af5e209ca47aa4/TxlData/SubstitutionMatchGroup.cs#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Honestly, this class was so complex, I just kinda skimmed it. Same with the tests.
If you want me to try to review logic, let me know. Maybe interactive would be best?
</blockquote></details>

Certainly can if you want. The unit tests give 100% coverage, so I'm fairly confident it's correct. However, if it was hard to understand, then maybe it's worth reviewing to see if there is a better way to skin the cat.  
___
*[`TxlData/TxlDataTests/SubstitutionMatchGroupTests.cs` line 102 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpuMLpnCL_UfiB0wddx:-NpvncSp8i6_3KrDFZXy:b-896fix) ([raw file](https://github.com/sillsdev/Transcelerator/blob/959007935c1458e61709ff2305af5e209ca47aa4/TxlData/TxlDataTests/SubstitutionMatchGroupTests.cs#L102)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> more tha once

typo
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/Transcelerator/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`TxlData/SubstitutionMatchGroup.cs` line 30 at r3](https://reviewable.io/reviews/sillsdev/Transcelerator/121#-NpuM5Gt9T_H6shsrM8b:-NpvqiWy5UOUUgOkGfLX:b-t9dway) ([raw file](https://github.com/sillsdev/Transcelerator/blob/959007935c1458e61709ff2305af5e209ca47aa4/TxlData/SubstitutionMatchGroup.cs#L30)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Certainly can if you want. The unit tests give 100% coverage, so I'm fairly confident it's correct. However, if it was hard to understand, then maybe it's worth reviewing to see if there is a better way to skin the cat.
</blockquote></details>

I was probably just being lazy.
But I did see it has lots of unit tests...
I can look again tomorrow if you like.
Or you can merge.

**Pull request merged**
