### PR TITLE
Miscellaneous cleanup

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/49)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/49)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[Transcelerator/UNSQuestionsDialog.cs, line 422 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/49#-MR6XMR53Q-oOsCmQmHX:-MR6XMR53Q-oOsCmQmHY:bjmh2jb) ([raw file](https://github.com/sillsdev/transcelerator/blob/f64afef4c6a1b72f51a07d37498c3e8b1b1ebb2a/Transcelerator/UNSQuestionsDialog.cs#L422)):*
> ```Smalltalk
> 		private void HandleStringsLocalized()
> 		{
> 			Text = Format(Text, m_projectName);
> ```

Will this work when called more than once (i.e. when the strings are localized)? If Text doesn't get reset, the format won't do anything (and it might as well have stayed in the constructor).

**Comment by tombogle** [comment]
___
*[Transcelerator/UNSQuestionsDialog.cs, line 422 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/49#-MR6XMR53Q-oOsCmQmHX:-MRPv2yCCjShnY343xWO:b-ze2d9q) ([raw file](https://github.com/sillsdev/transcelerator/blob/f64afef4c6a1b72f51a07d37498c3e8b1b1ebb2a/Transcelerator/UNSQuestionsDialog.cs#L422)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Will this work when called more than once (i.e. when the strings are localized)? If Text doesn't get reset, the format won't do anything (and it might as well have stayed in the constructor).
</blockquote></details>

My understanding is that with L10nSharp, if the StringsLocalized event fires, all the strings are reset. Certainly, this is consistent with how we do it in other places and other apps. If in some scenario it does not get reset, this at least won't do anything bad. All that said, I just now tried it and realized that in Transcelerator I never bothered to hook up on-the-fly localization. (I guess my assumption is that now Crowdin-based localization is "better.") So unless/until that happens, the event will never get fired and it's totally a moot point. Still, I guess since I went to the trouble of doing it, I might as well keep it, in case some day I do make on-the-fly localization possible.

**Comment by tombogle** [comment]
___
*[Transcelerator/UNSQuestionsDialog.cs, line 422 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/49#-MR6XMR53Q-oOsCmQmHX:-MRQaUObC71Vu6SP2Euh:brueyie) ([raw file](https://github.com/sillsdev/transcelerator/blob/f64afef4c6a1b72f51a07d37498c3e8b1b1ebb2a/Transcelerator/UNSQuestionsDialog.cs#L422)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

My understanding is that with L10nSharp, if the StringsLocalized event fires, all the strings are reset. Certainly, this is consistent with how we do it in other places and other apps. If in some scenario it does not get reset, this at least won't do anything bad. All that said, I just now tried it and realized that in Transcelerator I never bothered to hook up on-the-fly localization. (I guess my assumption is that now Crowdin-based localization is "better.") So unless/until that happens, the event will never get fired and it's totally a moot point. Still, I guess since I went to the trouble of doing it, I might as well keep it, in case some day I do make on-the-fly localization possible.
</blockquote></details>

I was partly right, partly wrong, and partly mistaken. It is possible to do on-the-fly translation in Transcelerator. Although it's not exposed in the UI, if the user were to know to press Shift+Alt and click on a button or whatever in the UI, the dialog to do localization does open. In theory, if they changed the Text of the main window, it would have the updated value in HandleStringsLocalized, so the re-formatting would work. However, Text is marked as NotLocalizable, so they can't change it. I debated making it localizable, but since all it is is a simple format string with a dash separating the product name and the project name (and the product name itself should not be localized anyway), it didn't seem very worthwhile. So I put this line of code back where it used to be.

**Review by FoolRunning — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/49#-:-MRQwA-ND_-wQhsZ6aQp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @FoolRunning)

**Review by FoolRunning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
