### PR TITLE
Implemented HTML help system

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/31)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 56 of 56 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/31)* status: all files reviewed, 11 unresolved discussions (waiting on @tombogle)

___
*[Docs/Help Topics/biblicalterms.htm, line 26 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYE7ByEaBuxjzEg66w:-MQYE7ByEaBuxjzEg66x:b-vw10yz) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/biblicalterms.htm#L26)):*
> ```HTML
> <ul>
>   <li>Right-click the corresponding occurrence of the term in the Biblical Terms Pane, and in the context menu, select <span class="ui">Add Rendering</span>. In the <span class="ui">Add Rendering</span> dialog box, type the desired rendering, and then click <span class="ui">OK</span>. The newly added rendering will be selected and will automatically replace the previous rendering in the translation.</li>
>   <li>Simply type the desired word in the translation, replacing the default rendering. If the term is not rendered directly in your translation or the rendering you typed is not likely to be useful for other questions that might use that term, there might be very little need to add it as a rendering. Note however that since Transcelerator will not be able to identify any part of the translation as a rendering of that term, no rendering will be selected for that occurrence of the biblical term and it will not be possible for Transcelerator to process this translation as model for other questions that might have the same frame.</li>
> ```

"translation as model" should be "translation as a model"?
___
*[Docs/Help Topics/featureoverview.htm, line 18 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYOg8z4UJzDhKfaNjD:-MQYOg9-9C8x2r8nt7xB:b-ygj30l) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/featureoverview.htm#L18)):*
> ```HTML
> <ul class="icon-list">
>   <li><i class="material-icons">save</i><span class="ui">Save</span> on demand or <span class="ui">Auto Save</span> saves every time a translation is changed (on by default)</li>
>   <li><i class="material-icons">refresh</i><span class="ui">Reload</span> forces a re-analysis of the questions< to improve guessed translations (after manual editing or addition of questions)/li>
> ```

spurious less than '<' in the text. Looks like it belongs to the ending **/li>** tag
___
*[Docs/Help Topics/featureoverview.htm, line 24 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYPKxr-pZfiMXZ-l07:-MQYPKxr-pZfiMXZ-l08:b-c6e1qh) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/featureoverview.htm#L24)):*
> ```HTML
> 
> <h3>Editing/Navigation</h3>
> <p>On the <span class="ui">Edit</span> menu, select <span class="ui">Previous Untranslated Question</span> and <span class="ui">Next Untranslated Question</span> to go to the next question that does not yet have a confirmed translation. When editing a translation use <span class="ui">Shift Word(s) Right</span> and <span class="ui">Shift Word(s) Right</span> to <a href="reorderingwords.htm"><i class="material-icons">compare_arrows</i>reorder the current or selected word</a>. On the toolbar there are also two buttons that allow the user to control whether to send () and receive () Scripture references to keep Transcelerator in sync with other applications (e.g., Paratext) when navigating.</p>
> ```

"Shift Word(s) Right" and "Shift Word(s) Right". I'm assuming one should be "Shift Word(s) Left".
___
*[Docs/Help Topics/filtering.htm, line 39 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYROjLCbhbgk5fxlkd:-MQYROjLCbhbgk5fxlke:bfgh2ac) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/filtering.htm#L39)):*
> ```HTML
> 
> <h3>Filter Status</h3>
> <p>The rightmost portion of toolbar in the main widnow indicates whether the data is currently filtered or unfiltered. Next to that you can see the number of questions that remain to be translated of those currently showing. If there is a filter set, these counts will include only those questions that match the the filter.</p>
> ```

"match the the filter"
___
*[Docs/Help Topics/generatescript.htm, line 25 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYXA1z-51Up-TYDf2G:-MQYXA2-CVmh7TbU5yQq:bn29qby) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/generatescript.htm#L25)):*
> ```HTML
> 		<li>Respondent receives individual questions and corresponding text portions via SMS, e-mail, etc. and responds ad-hoc</li>
> 	</ul>
> 	For some projects it might be necessary to use more than one approach to obtain the appropriate feedback. Transcelerator can be used to help facilitate any of these approaches, but there is no complete solution has been identified to automate the last approach.
> ```

"there is no complete solution has been"
___
*[Docs/Help Topics/generatescript.htm, line 45 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYXu-H6h9blX-ExtYc:-MQYXu-H6h9blX-ExtYd:burmr73) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/generatescript.htm#L45)):*
> ```HTML
> 	<ul>
> 		<li>If you will be working with a separate printout or pre-printed booklet with the Scripture text to be checked, you can save paper by clearing the <span class="ui">Include Entire Passage at the Start of Section</span> option.</li>
> 		<li>Verse numbers can be a helpful reference, but they can also be distracting, especially for newer readers and those not familiar with the tradition of using verse numbers in Bibles, so Transcelerator omits them by default. If check will be conducted by an interviewer who wants to be able to see the verse numbers or the verse numbers will not pose a problem for the respondent, select the <span class="ui">Include verse numbers</span> option.</li>
> ```

"If check will be"
___
*[Docs/Help Topics/generatescript.htm, line 58 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYYfI2AtdFNXASu5GB:-MQYYfI300mWqHC9WykP:br5u8r7) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/generatescript.htm#L58)):*
> ```HTML
> 	<li>Go to the <span class="ui">Appearance</span> tab to change the formatting used in the script:</li>
> 	<ul>
> 		<li>The HTML script uses <a href="https://www.w3.org/Style/CSS/">Cascading Style Sheets (CSS)</a> to control formating of the text. To enable the script to be emailed as a single file without loss of the formatting information, by default Transcelerator embeds the style sheet informtation in the HTML. If you want to have greater control over the appearance of your scripts, select the <span class="ui">Use and External CSS File</span> option. The first time you do this, Transcelerator will generate the default style sheet. You can then edit the style sheet as needed and use it for all future scripts to obtain a consistent look. If you ever need to revert to the default, simply select the <span class="ui">Overwrite Existing CSS File</span> option.</li>
> ```

"Use and External CSS File"
___
*[Docs/Help Topics/gettingstarted.htm, line 21 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYL9966lyuxG8w9GAt:-MQYL9966lyuxG8w9GAu:b-eq0nor) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/gettingstarted.htm#L21)):*
> ```HTML
> href="https://paratext.org/">Paratext</a>. If you have properly associated your Paratext project with the appropriate keyboard for entering vernacular text, this same keyboard will be activated when translating questions in Transcelerator.</p>
> <p>
> To run Transcelerator, first open the desired project (not a reference project) in Paratext. Go to <span class="ui">Tools</span> for that project and select <span class="ui">Transcelerator</span>. <span class="note">Note: In Paratext 9 and later, the menu icon <i class="material-icons">menu</i> is in the upper left corner of the title bar for the project window.</span></p>
> ```

Did you mean a "resource project" instead of a "reference project"?
___
*[Docs/Help Topics/Home.htm, line 38 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYMCmc9qxR8Q6BfotP:-MQYMCmd7TnXHttHezS2:bqxqfpw) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/Home.htm#L38)):*
> ```HTML
> <h3>How it Works</h3>
> <p>
> Transcelerator presents a translator with a list of comprehension questions. The user fills in translations of those questions, optionally selecting from existing known renderings of key <a href="biblicalterms.htm"><i class="material-icons">history_edu</i>biblical terms</a>. As work progresses, Transcelerator uses the biblical terms and growing body of translated questions to make guess at the translations of remaining questions.</p>
> ```

"to make guess at" seems incorrect.
___
*[Docs/Help Topics/renderingselectionrules.htm, line 36 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYdi4mBm-JcmapWlF7:-MQYdi4mBm-JcmapWlF8:b5pwkon) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/renderingselectionrules.htm#L36)):*
> ```HTML
> 	  <li><span class="ui">Term is immediately preceded by a specific word</span> - probably most likely to be useful with English prepositions (e.g., <span class="literal">for</span>, <span class="literal">from</span>, etc.), when the target vernacular uses a specific case for objects of a proposition and that case can be easily identified by affixation.</li>
> 	  <li><span class="ui">Term is immediately followed by a specific word</span> - useful for English terms that are frequently paired with a word such as <span class="literal">girl</span> that conveys gender or some other meaning that is marked in a regular way in the target vernacular.</li>
> 	  <li><span class="ui">User-defined condition</span> - the most flexible option, for any condition you can find a way to express using a regular expression. <span class="note">Note: If you select this option, the <span class="ui">OK</span> button will be unavailable until an expression is entered that contains the <span class="text-to-type">{0}</span> placeholder the represents the biblical term. (This will be the entire surface form of the English term as it occurs in a question.) Although <span class="literal">{0}</span> is not legal regular-expression syntax, Transcelerator will properly interpret it in the context of the surrounding valid regular expression. After clicking <span class="ui">OK</span>, if the regular expression seems to be invalid, a message will appear describing the apparent problem.</span></li>
> ```

"placeholder the represents the biblical term"
___
*[Transcelerator/MasterQuestionParser.cs, line 696 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQXACEw3mFTtjy6tnMT:-MQXACEx0h_VXeGCj9yc:b-91vpk7) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Transcelerator/MasterQuestionParser.cs#L696)):*
> ```Smalltalk
>                         }
> 						if (q.StartRef == 0 || q.EndRef == 0)
> 							Debug.WriteLine(q.Text);
> ```

Is this a problem in release mode?

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/31)* status: 48 of 56 files reviewed, 11 unresolved discussions (waiting on @FoolRunning)

___
*[Docs/Help Topics/biblicalterms.htm, line 26 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYE7ByEaBuxjzEg66w:-MQYjz0p4GvD3OAiWtzv:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/biblicalterms.htm#L26)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"translation as model" should be "translation as a model"?
</blockquote></details>

Done.
___
*[Docs/Help Topics/featureoverview.htm, line 18 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYOg8z4UJzDhKfaNjD:-MQYkCFw1RCh3YHbS76s:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/featureoverview.htm#L18)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

spurious less than '<' in the text. Looks like it belongs to the ending **/li>** tag
</blockquote></details>

Done.
___
*[Docs/Help Topics/featureoverview.htm, line 24 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYPKxr-pZfiMXZ-l07:-MQYkPol88AiA3IQzLhD:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/featureoverview.htm#L24)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"Shift Word(s) Right" and "Shift Word(s) Right". I'm assuming one should be "Shift Word(s) Left".
</blockquote></details>

Done.
___
*[Docs/Help Topics/filtering.htm, line 39 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYROjLCbhbgk5fxlkd:-MQYkXnvCd7gJTLApdT-:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/filtering.htm#L39)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"match the the filter"
</blockquote></details>

Done.
___
*[Docs/Help Topics/generatescript.htm, line 25 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYXA1z-51Up-TYDf2G:-MQYkici3a3n8hFpZBal:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/generatescript.htm#L25)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"there is no complete solution has been"
</blockquote></details>

Done.
___
*[Docs/Help Topics/generatescript.htm, line 45 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYXu-H6h9blX-ExtYc:-MQYkwG3-21cs5H87ryx:b-pkn3vq) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/generatescript.htm#L45)):*
> If check will be
I think it kind of almost makes sense as it is, but it would be better to say "If the check will be" or "If checking will be". I chose the latter.
___
*[Docs/Help Topics/generatescript.htm, line 58 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYYfI2AtdFNXASu5GB:-MQYlDzO3DaSe8pP_m4r:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/generatescript.htm#L58)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"Use and External CSS File"
</blockquote></details>

Done.
___
*[Docs/Help Topics/gettingstarted.htm, line 21 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYL9966lyuxG8w9GAt:-MQYlODd3SObU7STZ6hk:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/gettingstarted.htm#L21)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Did you mean a "resource project" instead of a "reference project"?
</blockquote></details>

Done.
___
*[Docs/Help Topics/Home.htm, line 38 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYMCmc9qxR8Q6BfotP:-MQYl_xG7cutk7rgW3sF:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/Home.htm#L38)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"to make guess at" seems incorrect.
</blockquote></details>

Done.
___
*[Docs/Help Topics/renderingselectionrules.htm, line 36 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQYdi4mBm-JcmapWlF7:-MQYlnyaDP48aFCha6NO:b-896fix) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Docs/Help Topics/renderingselectionrules.htm#L36)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

"placeholder the represents the biblical term"
</blockquote></details>

Done.
___
*[Transcelerator/MasterQuestionParser.cs, line 696 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/31#-MQXACEw3mFTtjy6tnMT:-MQYlsNJDXv9vCFqTAx1:b-cquqvo) ([raw file](https://github.com/sillsdev/transcelerator/blob/64aef9a0df33faa84a2da10b58878ebee0179d5c/Transcelerator/MasterQuestionParser.cs#L696)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Is this a problem in release mode?
</blockquote></details>

Just something I stuck in to have a place to set a breakpoint. There's a new data integrity check to prevent it now. I'll remove it.

**Review by FoolRunning — COMMENTED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/31#-:-MQYoGF8-YF3tTslH800:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FoolRunning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/31#-:-MQYoW1VBIhgMNQJOVd7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
