### PR TITLE
Ensure that questions have an immutable key that ScriptureForge can reference

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/23)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/23)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[ComprehensionCheckingData/ComprehensionCheckingQuestions.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/23#-MKLlkGPAyZzIIaZS78c:-MKLlkGPAyZzIIaZS78d:b-28nqyb) ([raw file](https://github.com/sillsdev/transcelerator/blob/92746b88ed67ead09d0d997d6d8ae24a97305e2a/ComprehensionCheckingData/ComprehensionCheckingQuestions.cs#L51)):*
> ```Smalltalk
> 		public string BookId { get; set; }
> 
> 		[XmlElement(ElementName = "Question")]
> ```

I think this change breaks backwards-compatibility with 1.0 ("Question" versus "Questions") and yet your Version setter still claims to support 1.0.
___
*[Transcelerator/PhraseCustomization.cs, line 228 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/23#-MKLoEr428bnVD70ohwn:-MKLoEr428bnVD70ohwo:b-2cneuw) ([raw file](https://github.com/sillsdev/transcelerator/blob/47ca77717c6fcd21bdbfba26790e8fc556458a16/Transcelerator/PhraseCustomization.cs#L228)):*
> ```Smalltalk
> 				}
> 
> 				return hashCode;
> ```

I'm not sure this hashing will work well. A different hash should not be produced if two items are equal. It seems like there are quite a few ways to make the Equals and GetHashCode diverge (i.e. Equals could return true while different hashes are generated). For example, it looks like two items would be considered equal if they had the same reference and ModifiedPhrase, but would produce different hashes if those same items had different types.
___
*[Transcelerator/UNSQuestionsDialog.cs, line 1491 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/23#-MKLqBuDB475IQT_SI_T:-MKLqBuE5SEcCey3k3FO:bnw08kf) ([raw file](https://github.com/sillsdev/transcelerator/blob/47ca77717c6fcd21bdbfba26790e8fc556458a16/Transcelerator/UNSQuestionsDialog.cs#L1491)):*
> ```Smalltalk
> 					Id = phrase.IsUserAdded ?
> 						phrase.QuestionInfo.Id :
> 						phrase.QuestionInfo?.Alternatives?.FirstOrDefault(a => a.IsKey)?.Text,
> ```

A null ID is fine?

**Comment by tombogle** [comment]
___
*[Transcelerator/UNSQuestionsDialog.cs, line 1491 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/23#-MKLqBuDB475IQT_SI_T:-MKa5Tt3CFPuPxghRKzb:b8z080a) ([raw file](https://github.com/sillsdev/transcelerator/blob/47ca77717c6fcd21bdbfba26790e8fc556458a16/Transcelerator/UNSQuestionsDialog.cs#L1491)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

A null ID is fine?
</blockquote></details>

If you look at the getter for Id, you'll see that if it is not set explicitly, it gets the English version of the question. That's actually the "normal" case.

**Comment by tombogle** [comment]
___
*[ComprehensionCheckingData/ComprehensionCheckingQuestions.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/23#-MKLlkGPAyZzIIaZS78c:-MKa5r9j0jUj63pZnHAj:b-6b2g6a) ([raw file](https://github.com/sillsdev/transcelerator/blob/92746b88ed67ead09d0d997d6d8ae24a97305e2a/ComprehensionCheckingData/ComprehensionCheckingQuestions.cs#L51)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I think this change breaks backwards-compatibility with 1.0 ("Question" versus "Questions") and yet your Version setter still claims to support 1.0.
</blockquote></details>

I've reverted that change now.

**Comment by tombogle** [comment]
___
*[Transcelerator/PhraseCustomization.cs, line 228 at r1](https://reviewable.io/reviews/sillsdev/transcelerator/23#-MKLoEr428bnVD70ohwn:-MKaB6W49J6XT8AIagkU:b-uxiq6c) ([raw file](https://github.com/sillsdev/transcelerator/blob/47ca77717c6fcd21bdbfba26790e8fc556458a16/Transcelerator/PhraseCustomization.cs#L228)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

I'm not sure this hashing will work well. A different hash should not be produced if two items are equal. It seems like there are quite a few ways to make the Equals and GetHashCode diverge (i.e. Equals could return true while different hashes are generated). For example, it looks like two items would be considered equal if they had the same reference and ModifiedPhrase, but would produce different hashes if those same items had different types.
</blockquote></details>

Modified Phrase should always be null for Deletions and never be null for the other three types. Unless one of the two types is a Deletion, the type does not figure into the question of equality. This means that whether you add, insert, or change an existing question, for a given Scripture reference the ModifiedPhrase must be unique. But since the ModifiedPhrase is null for a Deletion, for the case of Deletion, we need to look at the OriginalPhrase to ensure the same phrase isn't being deleted twice. FWIW, I did try the simpler and more logical looking approach of always including the type in the Hash, but that actually causes a test to fail because a single custom question is treated as both an addition and an insertion, and since they then generate different hashes, it allows both of them to be added to the HashSet.

**Review by FoolRunning — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 3 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/23#-:-MKaKwsQ5J-OZiMR0NwP:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
