### PR TITLE
TXL-19: Added more Spanish translations, updated installer for L10n

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/17)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/17)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 26 of 26 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/transcelerator/17)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[DistFiles/localization/Transcelerator.es.xlf, line 3 at r4](https://reviewable.io/reviews/sillsdev/transcelerator/17#-MHvTRh7CSGVCUcooKGV:-MHvTRh83eILH_U88f6-:b-ro5ohr) ([raw file](https://github.com/sillsdev/transcelerator/blob/5e57dd9ed568f0d0abe5d65fd8fc6fb8342c3981/DistFiles/localization/Transcelerator.es.xlf#L3)):*
> ```
> target-language="es-ES"
> ```
Have you looked at the implications of this being country-specific? 
I guess it would only affect if we auto select that language based on the user's OS locale?

**Comment by tombogle** [comment]
___
*[DistFiles/localization/Transcelerator.es.xlf, line 3 at r4](https://reviewable.io/reviews/sillsdev/transcelerator/17#-MHvTRh7CSGVCUcooKGV:-MHwEdYBAwbSUP06I1Aw:b-4r15et) ([raw file](https://github.com/sillsdev/transcelerator/blob/5e57dd9ed568f0d0abe5d65fd8fc6fb8342c3981/DistFiles/localization/Transcelerator.es.xlf#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> target-language="es-ES"
> ```
Have you looked at the implications of this being country-specific? 
I guess it would only affect if we auto select that language based on the user's OS locale?
</blockquote></details>

It's an annoying reality of the way crowdin handles Spanish. I don't know why, but if you pick generic Spanish (no country), it treats it as es-ES. They have options for lots of individual Latin American countries, but no separate option for Spain. L10nSharp seems to have the needed smarts to do fallback between es and es-ES (and other similar things for other languages. Transcelerator inherits its UI language from Paratext if the user hasn't overridden it, and I have verified that choosing Spanish in Paratext does cause Spanish to be the default in TXL. So I think we're good.

**Pull request merged**
